import { Hono } from 'hono'
import type { Env } from '../types/env'

const app = new Hono<{ Bindings: Env }>()

/**
 * Root endpoint handler for legacy client bootstrap
 * Serves minimal HTML that detects fragment-based URLs and upgrades to server-side redirects
 */
app.get('/', (c) => {
  const html = generateBootstrapHTML()
  return c.html(html, {
    headers: {
      'Cache-Control': 'no-cache, no-store, must-revalidate',
      'Pragma': 'no-cache',
      'Expires': '0'
    }
  })
})

/**
 * Generate bootstrap HTML with inline JavaScript for URL upgrade
 */
function generateBootstrapHTML(): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="robots" content="noindex, nofollow">
    <title>Redirecting...</title>
    <script>
    // get redirect url (part after #)
    var path = window.location.href;
    var hashInd = path.indexOf("#");
    var redirectUrl = path.slice(hashInd + 1);

    // get isNoRedirect value (0 or 1): https://stackoverflow.com/questions/901115/how-can-i-get-query-string-values-in-javascript/901144#901144
    var queryParams = new URLSearchParams(window.location.search);
    var isNoRedirect = queryParams.get("isNoRedirect");
    var isRedirect = !Boolean(parseInt(isNoRedirect));

    setTimeout(function () {
      var newLocation = '/r?to=' + redirectUrl;

      if (isRedirect && newLocation !== "") {
        window.location.href = newLocation;
      }
    }, 200);
  </script>
    <noscript>
        <div style="font-family: Arial, sans-serif; text-align: center; margin-top: 50px;">
            <h1>JavaScript Required</h1>
            <p>Please enable JavaScript to continue with the redirect.</p>
            <p>This service requires JavaScript to upgrade legacy URLs to our secure redirect system.</p>
        </div>
    </noscript>
    <style>
        body {
            margin: 0;
            padding: 0;
            background-color: #f5f5f5;
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
        }
        noscript div {
            max-width: 500px;
            margin: 100px auto;
            padding: 40px;
            background: white;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }
        h1 {
            color: #333;
            margin-bottom: 16px;
        }
        p {
            color: #666;
            line-height: 1.5;
        }
    </style>
</head>
<body>
    <!-- Content is generated by JavaScript above -->
</body>
</html>`
}

export default app