import { Hono } from 'hono'
import { RedirectError } from '../lib/errors'
import type { Env } from '../types/env'

const app = new Hono<{ Bindings: Env }>()

/**
 * Root endpoint handler for legacy client bootstrap
 * Serves minimal HTML that detects fragment-based URLs and upgrades to server-side redirects
 */
app.get('/', (c) => {
  // Check if user has disabled redirects via isNoRedirect parameter
  const isNoRedirect = c.req.query('isNoRedirect') === '1'
  
  // If there's a hash, serve HTML with JavaScript upgrade script
  if (c.req.url.includes('#')) {
    const html = generateBootstrapHTML(c.req.url, isNoRedirect)
    return c.html(html, {
      headers: {
        'Cache-Control': 'no-cache, no-store, must-revalidate',
        'Pragma': 'no-cache',
        'Expires': '0'
      }
    })
  }
  
  // If no hash, redirect to default URL or show error if not configured
  const defaultUrl = c.env.DEFAULT_REDIRECT_URL
  
  if (!defaultUrl) {
    throw new RedirectError(
      'No destination URL provided and no default redirect configured',
      400,
      'MISSING_DESTINATION'
    )
  }
  
  return c.redirect(defaultUrl, 302)
})

/**
 * Generate bootstrap HTML with inline JavaScript for URL upgrade
 */
function generateBootstrapHTML(requestUrl: string, isNoRedirect: boolean): string {
  // Extract the hash portion for the upgrade script
  const urlWithHash = new URL(requestUrl)
  const hash = urlWithHash.hash || ''
  
  return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="robots" content="noindex, nofollow">
    <title>Redirecting...</title>
    <script>
        // Minimal bootstrap script to upgrade legacy fragment URLs to server-side redirects
        (function() {
            var currentHash = ${JSON.stringify(hash)};
            var isNoRedirect = ${isNoRedirect ? 'true' : 'false'};
            
            if (currentHash && currentHash.length > 1) {
                // Extract destination from hash (remove # prefix)
                var destination = currentHash.substring(1);
                
                // URL encode the destination for safe transport
                var encodedDestination = encodeURIComponent(destination);
                
                // Build the upgrade URL with original parameters preserved
                var upgradeUrl = '/r?to=' + encodedDestination;
                
                // Add debug parameter if isNoRedirect was set
                if (isNoRedirect) {
                    upgradeUrl += '&n=1';
                }
                
                // Upgrade to server-side redirect
                window.location.replace(upgradeUrl);
            } else {
                // No hash found - this should be handled by the server redirect
                document.body.innerHTML = '<h1>Redirecting...</h1><p>Please wait while we redirect you.</p>';
            }
        })();
    </script>
    <noscript>
        <div style="font-family: Arial, sans-serif; text-align: center; margin-top: 50px;">
            <h1>JavaScript Required</h1>
            <p>Please enable JavaScript to continue with the redirect.</p>
            <p>This service requires JavaScript to upgrade legacy URLs to our secure redirect system.</p>
        </div>
    </noscript>
    <style>
        body {
            margin: 0;
            padding: 0;
            background-color: #f5f5f5;
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
        }
        noscript div {
            max-width: 500px;
            margin: 100px auto;
            padding: 40px;
            background: white;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }
        h1 {
            color: #333;
            margin-bottom: 16px;
        }
        p {
            color: #666;
            line-height: 1.5;
        }
    </style>
</head>
<body>
    <!-- Content is generated by JavaScript above -->
</body>
</html>`
}

export default app