workflow: retrospective
step: 1
status: completed
completed_epic: 7
detection_method: auto
partial_retrospective: false
sources:
  - docs/sprint-status.yaml
summary:
  epic_status: contexted
  retrospective_status: optional
  total_stories: 7
  done_stories: 7
  pending_stories: 0
notes: |
  Epic 7 detected as most recently completed based on story files and sprint-status.
  All seven stories for Epic 7 are marked done. Proceeding with full retrospective.
