development_status:
  epic-1: backlog
  1-1-project-initialization-with-hono-framework: backlog
  1-2-kv-data-structure-and-crud-operations: backlog
  1-3-basic-r-endpoint-with-redirect-logic: backlog
  1-4-custom-error-classes-and-global-error-handler: backlog
  1-5-redirect-type-support-301-vs-302: backlog
  epic-1-retrospective: optional

  epic-2: backlog
  2-1-tracking-placeholder-stubs-and-flags: backlog
  epic-2-retrospective: optional

  epic-3: backlog
  3-1-client-side-bootstrap-html-at-root-endpoint: backlog
  3-2-legacy-url-backward-compatibility-testing: backlog
  epic-3-retrospective: optional

  epic-4: backlog
  epic-4-retrospective: optional

  epic-5: backlog
  5-1-debug-mode-implementation-for-redirect-endpoint: backlog
  5-2-structured-logging-infrastructure: backlog
  epic-5-retrospective: optional

  epic-6: backlog
  6-1-zod-schema-validation-with-hono-validator-middleware: backlog
  6-2-protocol-validation-and-open-redirect-prevention: backlog
  6-3-optional-domain-allowlist-configuration: backlog
  epic-6-retrospective: optional

  epic-7: backlog
  7-1-tracking-parameter-extraction-from-destination-urls: backlog
  7-2-analytics-provider-interface-and-neutral-event-model: backlog
  7-3-analytics-router-multi-service-fan-out: backlog
  7-4-provider-registry-feature-flags-env-config: backlog
  7-5-timeout-reliability-policy-non-blocking: backlog
  7-6-observability-structured-logs-basic-counters: backlog
  7-7-test-harness-provider-mocks: backlog
  epic-7-retrospective: optional

  epic-8: backlog
  8-1-ga4-measurement-protocol-payload-builder: backlog
  8-2-ga4-measurement-protocol-http-integration: backlog
  8-3-integrated-ga4-in-redirect-flow: backlog
  epic-8-retrospective: optional
